name: refresh caches

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      data-repository:
        required: true
        type: string
    secrets:
      ATCODER_USERNAME:
        required: true
      ATCODER_PASSWORD:
        required: true

jobs:
  refresh-caches:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_PATH: ./ac-predictor-data # TODO: make absolute paths
    steps:
      - name: Checkout crawler
        uses: actions/checkout@v4
        with:
          path: ac-predictor

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.data-repository }}
          path: ac-predictor-data
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install crawler
        run: |
          pip install -e ac-predictor/crawler

      - name: Setup crawler
        run: |
          git config --global user.name ac-predictor
          git config --global user.email kymn0116+ac-predictor@gmail.com
          echo '${{ secrets.ATCODER_PASSWORD }}' | ac-predictor-crawler login '${{ secrets.ATCODER_USERNAME }}'

      - name: Run crawler
        run: ${{ inputs.command }}
