name: update aperfs

on:
  workflow_dispatch: # for debugging
  schedule:
    # offsets the crawl to deal with the congestion before the start of the contest
    - cron: '27-59/30 * * * *'

jobs:
  update-aperfs:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_PATH: ./ac-predictor-data # TODO: make absolute paths
    steps:
      - name: Crawl
        secrets:
          ATCODER_USERNAME: ${{ secrets.ATCODER_USERNAME }}
          ATCODER_PASSWORD: ${{ secrets.ATCODER_PASSWORD }}
        uses: ./.github/workflows/run-crawler.yaml
        with:
          data-repository: key-moon/ac-predictor-data
          command: |
            ac-predictor-crawler-runner update-aperfs
            curl -fsS -m 10 --retry 5 https://hc-ping.com/${{ secrets.UPDATE_APERFS_UUID }}/$?
