name: update aperfs

on:
  workflow_dispatch: # for debugging
  schedule:
    # offsets the crawl to deal with the congestion before the start of the contest
    - cron: '27-59/30 * * * *'

jobs:
  update-aperfs:
    uses: ./.github/workflows/run-crawler.yaml
    with:
      data-repository: key-moon/ac-predictor-data
      command: ac-predictor-crawler-runner update-aperfs
    secrets:
      ATCODER_USERNAME: ${{ secrets.ATCODER_USERNAME }}
      ATCODER_PASSWORD: ${{ secrets.ATCODER_PASSWORD }}
      HEALTHCHECK_UUID: ${{ secrets.UPDATE_APERFS_UUID }}
      DATA_DEPLOY_KEY: ${{ secrets.DATA_DEPLOY_KEY }}
