name: update caches

on:
  workflow_dispatch: # for debugging
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-aperfs:
    uses: ./.github/workflows/run-crawler.yaml
    with:
      data-repository: key-moon/ac-predictor-data
      command: ac-predictor-crawler-runner crawl-results
    secrets:
      ATCODER_USERNAME: ${{ secrets.ATCODER_USERNAME }}
      ATCODER_PASSWORD: ${{ secrets.ATCODER_PASSWORD }}
      HEALTHCHECK_UUID: ${{ secrets.CRAWL_RESULTS_UUID }}
      DATA_DEPLOY_KEY: ${{ secrets.DATA_DEPLOY_KEY }}
