name: refresh caches

on:
  workflow_dispatch: # for debugging
  schedule:
    - cron: '5 0 * * Sat'

jobs:
  update-aperfs:
    uses: ./.github/workflows/run-crawler.yaml
    with:
      data-repository: key-moon/ac-predictor-data
      command: ac-predictor-crawler-runner refresh-results
    secrets:
      ATCODER_SESSION: ${{ secrets.ATCODER_SESSION }}
      HEALTHCHECK_UUID: ${{ secrets.REFRESH_RESULTS_UUID }}
      DATA_DEPLOY_KEY: ${{ secrets.DATA_DEPLOY_KEY }}
